#
# Create Kubernetes Secrete
# Description:  create kubernetes secret for couchbase cluster admin username/password
#
# Kubernetes Secrets documentation:  https://kubernetes.io/docs/concepts/configuration/secret/
#
# Couchbase Operator documentation: https://docs.couchbase.com/operator/current/howto-couchbase-create.html 
#
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password