# read up on using workflow dispatch 
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

name: "Create cluster using KinD"
on: 
  workflow_dispatch

jobs:
  kind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: engineerd/setup-kind@v0.5.0
      - name: Install Helm
        uses: azure/setup-helm@v1
      - name: Install the operator 
        run: |
          helm repo add couchbase https://couchbase-partners.github.io/helm-charts/
          helm repo update
          helm install default --values deployment/operator-values.yaml couchbase/couchbase-operator
      - name: validate the pods for couchbase 
        run: |
          sleep 180 
          kubectl get pods -n default 